/*A*/
SELECT PROFESOR.DNI FROM PROFESOR JOIN DEPARTAMENTO USING(CODDEP) WHERE DEPARTAMENTO.NOMBRE='INFORMATICA Y COMUNICACIONES';
/*B*/
SELECT ALUMNO.NOMBRE, ALUMNO.PRAPELLIDO FROM ALUMNO JOIN ALUMNOBIL(DNI) WHERE UPPER(LUGAR) IN ('MADRID','BARCELONA');
/*C*/
SELECT ALUMNO.NOMBRE, ALUMNO.PRAPELLIDO, ALUMNO.SGAPELLIDO FROM ALUMNO JOIN MATRICULA ON ALUMNO.DNI=MATRICULA.DNI JOIN ASIGNATURA ON MATRICULA.CODASIG=ASIGNATURA.CODASIG WHERE UPPER(ASIGNATURA.NOMBRE) IN ('BASES DE DATOS','ACCESO A DATOS');
/*D*/
SELECT ALUMNO.NOMBRE, ALUMNO.PRAPELLIDO, ALUMNO.SGAPELLIDO FROM ALUMNO JOIN MATRICULA ON ALUMNO.DNI=MATRICULA.DNI JOIN ASIGNATURA ON MATRICULA.CODASIG=ASIGNATURA.CODASIG JOIN CICLO ON ASIGNATURA.CODCF=CICLO.CODCF WHERE SIGLAS='DAM' AND NOTA>=5;
/*E*/
SELECT AG.NOMBRE 
FROM ALUMNO AL
JOIN MATRICULA M ON AL.DNI=M.DNI
JOIN ASIGNATURA AG ON M.CODASIG=AG.CODASIG
JOIN IMPARTE I ON AG.CODASIG=I.CODASIG
JOIN PROFESOR P ON I.DNI = P.DNI
JOIN DEPARTAMENTO D ON P.CODDEP = D.CODDEP
WHERE NH>100 
AND SIGLAS='DAM' 
AND CICLO.NOMBRE='INFORMATICA Y COMUNICACION' 
AND MATRICULA.CURSO=2023
UNION
SELECT AG1.NOMBRE FROM ASIGNATURA AG1 JOIN CICLO C ON AG1.CODCF=C.CODCF
WHERE NH>100 
AND SIGLAS='DAM' 
AND CICLO.NOMBRE='INFORMATICA Y COMUNICACION' 
AND MATRICULA.CURSO=2023;
