/*A*/
SELECT PROFESOR.DNI FROM PROFESOR JOIN DEPARTAMENTO(CODDEP) WHERE DEPARTAMENTO.NOMBRE='INFORMATICA Y COMUNICACIONES';
/*B*/
SELECT ALUMNO.NOMBRE, ALUMNO.PRAPELLIDO FROM ALUMNO JOIN ALUMNOBIL(DNI) WHERE UPPER(LUGAR) IN ('MADRID','BARCELONA');
/*C*/
SELECT ALUMNO.NOMBRE, ALUMNO.PRAPELLIDO, ALUMNO.SGAPELLIDO FROM ALUMNO JOIN MATRICULA ON ALUMNO.DNI=MATRICULA.DNI JOIN ASIGNATURA ON MATRICULA.CODASIG=ASIGNATURA.CODASIG WHERE UPPER(ASIGNATURA.NOMBRE) IN ('BASES DE DATOS','ACCESO A DATOS');
/*D*/
SELECT ALUMNO.NOMBRE, ALUMNO.PRAPELLIDO, ALUMNO.SGAPELLIDO FROM ALUMNO JOIN MATRICULA ON ALUMNO.DNI=MATRICULA.DNI JOIN ASIGNATURA ON MATRICULA.CODASIG=ASIGNATURA.CODASIG JOIN CICLO ON ASIGNATURA.CODCF=CICLO.CODCF WHERE SIGLAS='DAM' AND NOTA>=5;
/*E*/
SELECT ASIGNATURA.NOMBRE FROM ASIGNATURA JOIN IMPARTE ON ASIGNATURA.CODASIG=IMPARTE.CODASIG JOIN PROFESOR ON IMPARTE.DNI=PROFESOR.DNI JOIN DEPARTAMENTO ON PROFESOR.CODDEP=DEPARTAMENTO.CODDEP, ALUMNO JOIN MATRICULA ON ALUMNO.DNI=MATRICULA.DNI JOIN ASIGNATURA SG ON MATRICULA.CODASIG=SG.CODASIG JOIN CICLO ON ASIGNATURA.CODCF=CICLO.CODCF WHERE NH>100 AND SIGLAS='DAM' AND CICLO.NOMBRE='INFORMATICA Y COMUNICACION' AND MATRICULA.CURSO=2023;