/*A*/
SELECT MAX(PRECIO) FROM LIBRO;
/*B*/
SELECT MIN(PRECIO) FROM LIBRO;
/*C*/
SELECT MIN(FECHA_SAL) FROM EDITA WHERE DNI=443042293;
SELECT MAX(FECHA_SAL) FROM EDITA WHERE DNI='29110302' ORDER BY FECHA_SAL ASC AND ROWNUM = 1;
/*D*/
SELECT MAX(FECHA_SAL) FROM EDITA WHERE DNI=29110302;
SELECT MAX(FECHA_SAL) FROM EDITA WHERE DNI='29110302' ORDER BY FECHA_SAL DESC AND ROWNUM = 1
/*E*/
SELECT MAX(NUMPAG) FROM LIBRO WHERE TEMATICA='NOVELA';
/*F*/
SELECT MIN(NUMPAG) FROM LIBRO WHERE TEMATICA IN('INFANTIL','CIENTIFICA','NOVELA','COMICO');
/*G*/
SELECT COUNT(*) FROM LIBRO WHERE TEMATICA='CIENTIFICO' AND PRECIO(BETWEEN 5 AND 15);