/*VISTAS*/
/*EJERCICIO 1*/
CREATE OR REPLACE VIEW PACIENTES_2024 AS SELECT P.NUMERO_PACIENTE FROM PACIENTE P JOIN EMERGENCIA E ON P.DNI_PACIENTE=E.DNI_PACIENTE JOIN AMBULANCIA A ON E.MATRICULA=A.MATRICULA WHERE E.SANIDAD='PUBLICA' AND TO_CHAR(A.FECHA_VALIDEZ_ITV, 'YYYY')=TO_CHAR(sysdate,'yyyy');
SELECT * FROM PACIENTES_2024;
SELECT NOMBRE FROM PACIENTE WHERE NUMERO_PACIENTE=1002;
/*EJERCICIO 2*/
CREATE OR REPLACE VIEW PACIENTESCONDUCTORES AS SELECT A.MATRICULA, P.DNI_PACIENTE FROM PACIENTE P JOIN EMERGENCIA E ON P.DNI_PACIENTE=E.DNI_PACIENTE JOIN AMBULANCIA A ON E.MATRICULA=A.MATRICULA WHERE TO_CHAR(E.FECHA, 'MM')<'03' AND P.DNI_PACIENTE IN (SELECT DNI_PACIENTE FROM PACIENTE WHERE PRAPELLIDO LIKE '%Z');
SELECT * FROM PACIENTESCONDUCTORES;
SELECT MATRICULA FROM PACIENTESCONDUCTORES;
/*EJERCICIO 3*/
CREATE VIEW PACIENTESPUBLICOSPRIVADOS AS SELECT A.MATRICULA, P.NOMBRE FROM PACIENTE P JOIN EMERGENCIA E ON P.DNI_PACIENTE=E.DNI_PACIENTE JOIN AMBULANCIA A ON E.MATRICULA=A.MATRICULA WHERE E.SANIDAD='PRIVADA' UNION SELECT A.MATRICULA, P.NOMBRE FROM PACIENTE P JOIN EMERGENCIA E ON P.DNI_PACIENTE=E.DNI_PACIENTE JOIN AMBULANCIA A ON E.MATRICULA=A.MATRICULA WHERE E.SANIDAD='PUBLICA';
SELECT * FROM PACIENTESPUBLICOSPRIVADOS;
SELECT NOMBRE FROM PACIENTESPUBLICOSPRIVADOS WHERE MATRICULA IN (SELECT MATRICULA FROM AMBULANCIA WHERE MATRICULA LIKE '%R');