CREATE OR REPLACE TYPE TDATOSPERSONALES AS OBJECT (
    CODIGO_DP NUMBER(3),
    NOMBRE_COMPLETO TNOMBRECOMPLETO,
    DOMICILIO TDOMICILIO,
    CODIGO_POSTAL TCODPOSTAL,
    FECHA_NACIMIENTO DATE,
    MEMBER PROCEDURE inicializarDatosPersonales(CODIGO_DP NUMBER, NOMBRE_COMPLETO TNOMBRECOMPLETO, DOMICILIO TDOMICILIO, CODIGO_POSTAL TCODPOSTAL, FECHA_NACIMIENTO DATE)
)NOT FINAL;

CREATE OR REPLACE TYPE BODY TDATOSPERSONALES AS
    MEMBER PROCEDURE inicializarDatosPersonales(CODIGO_DP NUMBER, NOMBRE_COMPLETO TNOMBRECOMPLETO, DOMICILIO TDOMICILIO, CODIGO_POSTAL TCODPOSTAL, FECHA_NACIMIENTO DATE) IS
    BEGIN
        SELF.CODIGO_DP := CODIGO_DP;
        SELF.NOMBRE_COMPLETO := NOMBRE_COMPLETO;
        SELF.DOMICILIO := DOMICILIO;
        SELF.CODIGO_POSTAL := CODIGO_POSTAL;
        SELF.FECHA_NACIMIENTO := FECHA_NACIMIENTO;
    END;
END;

CREATE TYPE profesor UNDER tdatospersonales (
    f_incorporacion DATE
);

CREATE TYPE alumno UNDER tDatosPersonales (
    calificaciones evaluaciones
);

CREATE TYPE evaluaciones UNDER tDatosPersonales(
    evaluacionUno NUMBER,
    evaluacionDos NUMBER,
    evaluacionTres NUMBER,
    evaluacionCuatro NUMBER
);
