CREATE OR REPLACE TYPE TCODPOSTAL AS OBJECT(
    LOCALIDAD NUMBER(3),
    PROVINCIA NUMBER(2)
);

CREATE OR REPLACE TYPE TDOMICILIO AS OBJECT(
    TIPODEVIA VARCHAR(50),
    NOMBREVIA VARCHAR(100),
    NUMERO NUMBER,
    RESTODOMICILIO VARCHAR2(100)
);

CREATE OR REPLACE TYPE TNOMBRECOMPLETO AS OBJECT(
    NOMBRE VARCHAR2(50),
    PRAPELLIDO VARCHAR2(50),
    SGAPELLIDO VARCHAR2(50)
);

CREATE OR REPLACE TYPE TDATOSPERSONALES AS OBJECT (
    CODIGO_DP NUMBER(3),
    NOMBRE_COMPLETO TNOMBRECOMPLETO,
    DOMICILIO TDOMICILIO,
    CODIGO_POSTAL TCODPOSTAL,
    FECHA_NACIMIENTO DATE
);