CREATE TABLE DIRECTOR(
    DNI_DIRECTOR VARCHAR(9)NOT NULL,
    NOMBRE VARCHAR(40)NOT NULL,
    APELLIDO1 VARCHAR(40)NOT NULL,
    APELLIDO2 VARCHAR(40)NULL,
    DOMICILIO VARCHAR(40)NOT NULL,
    EMAIL VARCHAR(40)NULL,
    CONSTRAINT PK_DIRECTOR PRIMARY KEY(DNI_DIRECTOR)
);

CREATE TABLE SUPERMERCADO(
    CODSUPERMERCADO NUMBER(3)NOT NULL,
    DIRECCION VARCHAR(40)NOT NULL,
    SUPERFICIE NUMBER(9)NOT NULL,
    ESALQUILER NUMBER(1)NOT NULL,
    FECHA DATE NOT NULL,
    DNI_DIRECTOR VARCHAR(9)NOT NULL,
    CONSTRAINT PK_SUPERMERCADO PRIMARY KEY(CODSUPERMERCADO),
    CONSTRAINT FK_DIRECTOR FOREIGN KEY(DNI_DIRECTOR) REFERENCES DIRECTOR(DNI_DIRECTOR),
    CONSTRAINT CK_ESALQUILER CHECK(ESALQUILER IN (0,1))
);

CREATE TABLE VENDEDOR(
    DNI_VENDEDOR VARCHAR(9)NOT NULL,
    NOMBRE VARCHAR(40)NOT NULL,
    APELLIDO1 VARCHAR(40)NOT NULL,
    APELLIDO2 VARCHAR(40)NULL,
    DOMICILIO VARCHAR(40)NOT NULL,
    EMAIL VARCHAR(40)NULL,
    CODSUPERMERCADO NUMBER(3)NOT NULL,
    CONSTRAINT PK_VENDEDOR PRIMARY KEY(DNI_VENDEDOR),
    CONSTRAINT FK_SUPERMERCADO FOREIGN KEY(CODSUPERMERCADO)REFERENCES SUPERMERCADO(CODSUPERMERCADO)
);

CREATE TABLE CLIENTE(
    DNI_CLIENTE VARCHAR(9)NOT NULL,
    NOMBRE VARCHAR(40)NOT NULL,
    APELLIDO1 VARCHAR(40)NOT NULL,
    APELLIDO2 VARCHAR(40)NULL,
    DOMICILIO VARCHAR(40)NOT NULL,
    EMAIL VARCHAR(40)NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY(DNI_CLIENTE)
);

CREATE TABLE VENTA(
    CODVENTA NUMBER(3)NOT NULL,
    FECHA DATE NOT NULL,
    DNI_VENDEDOR VARCHAR(9)NOT NULL,
    DNI_CLIENTE VARCHAR(9)NOT NULL,
    CONSTRAINT PK_VENTA PRIMARY KEY (CODVENTA),
    CONSTRAINT FK_VENDEDOR FOREIGN KEY(DNI_VENDEDOR) REFERENCES VENDEDOR(DNI_VENDEDOR),
    CONSTRAINT FK_CLIENTE FOREIGN KEY(DNI_CLIENTE) REFERENCES CLIENTE(DNI_CLIENTE)
);

ALTER TABLE VENTA 

CREATE TABLE PRODUCTO(
    CODPRODUCTO NUMBER(3)NOT NULL,
    DESCRIPCION VARCHAR(40)NOT NULL,
    FAMILIA VARCHAR(10)NOT NULL,
    GENERO CHAR(1)NOT NULL,
    DESCUENTO NUMBER(2) NULL,
    IVA NUMBER(2)NULL,
    CONSTRAINT PK_PRODUCTO PRIMARY KEY(CODPRODUCTO)
);

CREATE TABLE PRECIO(
    CODPRODUCTO NUMBER(3)NOT NULL,
    FECHA DATE NOT NULL,
    PRECIO NUMBER(3)NOT NULL,
    CONSTRAINT PK_PRECIO PRIMARY KEY(CODPRODUCTO, FECHA),
    CONSTRAINT FK_PRODCUTO FOREIGN KEY(CODPRODUCTO) REFERENCES PRODUCTO(CODPRODUCTO)
);

CREATE TABLE LINEAVENTA(
    CODVENTA NUMBER(3) NOT NULL,
    NUMLINEA NUMBER(3) NOT NULL,
    CODPRODUCTO NUMBER(3)NOT NULL,
    FECHA DATE NOT NULL,
    CONSTRAINT PK_LINEAVENTA PRIMARY KEY(CODVENTA, NUMLINEA),
    CONSTRAINT FK_VENTA FOREIGN KEY(CODVENTA, NUMLINEA) REFERENCES VENTA(CODVENTA, NUMLINEA),
    CONSTRAINT FK_PRODUCTO1 FOREIGN KEY(CODPRODUCTO) REFERENCES PRECIO(CODPRODUCTO),
    CONSTRAINT FL_FECHA FOREIGN KEY(FECHA) REFERENCES PRECIO(FECHA)
);

CREATE TABLE DEVOLUCION(
    CODVENTA NUMBER(3)NOT NULL,
    NUMLINEA NUMBER(3)NOT NULL,
    FECHA DATE NOT NULL,
    ESTADO VARCHAR(30)NOT NULL,
    TIPODEV VARCHAR(15)NOT NULL,
    CONSTRAINT PK_DEVOLUCION PRIMARY KEY(CODVENTA, NUMLINEA, FECHA),
    CONSTRAINT FK_LINEAVENTA FOREIGN KEY(CODVENTA) REFERENCES LINEAVENTA(CODVENTA),
    CONSTRAINT FK_NUMLINEA FOREIGN KEY(NUMLINEA) REFERENCES LINEAVENTA(NUMLINEA)
);