/*A*/
ALTER TABLE DIRECTOR ADD CONSTRAINT UQ_TELEFONO UNIQUE(TELEFONO);
ALTER TABLE DIRECTOR ADD CONSTRAINT UQ_EMAIL_DIRECTOR UNIQUE(EMAIL);
ALTER TABLE VENDEDOR ADD CONSTRAINT UQ_TELEFONO_VENDEDOR UNIQUE(TELEFONO);
ALTER TABLE VENDEDOR ADD CONSTRAINT UQ_EMAIL_VENDEDOR UNIQUE(EMAIL);
ALTER TABLE CLIENTE ADD CONSTRAINT UQ_TELEFONO_CLIENTE UNIQUE(TELEFONO);
ALTER TABLE CLIENTE ADD CONSTRAINT UQ_EMAIL_CLIENTE UNIQUE(EMAIL);
/*B*/
ALTER TABLE DIRECTOR MODIFY TELEFONO NUMBER(9);
ALTER TABLE CLIENTE MODIFY TELEFONO NUMBER(9);
ALTER TABLE VENDEDOR MODIFY TELEFONO NUMBER(9);

ALTER TABLE DIRECTOR ADD CONSTRAINT TELEFONO_DIGITOS CHECK (LENGTH(TELEFONO) = 9);
ALTER TABLE CLIENTE ADD CONSTRAINT TELEFONO_DIGITOS_CLIENTE CHECK (LENGTH(TELEFONO) = 9);
ALTER TABLE VENDEDOR ADD CONSTRAINT TELEFONO_DIGITOS_VENDEDOR CHECK (LENGTH(TELEFONO) = 9);
/*C*/
ALTER TABLE VENTA ADD CONSTRAINT UQ_DNI_VENCL CHECK(DNI_CLIENTE <> DNI_VENDEDOR);
/*D*/
ALTER TABLE PRODUCTO ADD CONSTRAINT UQ_DESCRIPCION_PRODUCTO UNIQUE(DESCRIPCION);
/*PARA CAMBIAR A NULO DEBEMOS ENTRAR EN LA TABLA QUE QUERAMOS CAMBIAR
LUEGO DAREMOS CLICK EN RESTRICCIONES Y DAREMOS AL LAPIZ PARA EDITAR 
LA RESTRCCION QUE QUERAMOS, LUEGO DAREMOS AL BORRAR Y SELECCIONAREMOS 
NULO*/
/*E*/
ALTER TABLE LINEAVENTA ADD CONSTRAINT CK_LINEAVENTA1 CHECK(NUMLINEAVENTA > 1 AND NUMLINEAVENTA < 99);