CREATE TABLE CLIENTE(
    DNI_CLIENTE VARCHAR(9) NOT NULL,
    NOMBRE VARCHAR(41) NOT NULL,
    AP1 VARCHAR(35) NOT NULL,
    AP2 VARCHAR(35) NULL,
    DIRECCION VARCHAR(35) NOT NULL,
    TELEFONO NUMBER(9) NOT NULL,
    EMAIL VARCHAR(9)NOT NULL
)

CREATE TABLE VENTA(
    CODVENTA NUMBER(3) NOT NULL,
    FECHA DATE NOT NULL,
    DNI_VENDEDOR VARCHAR(9) NOT NULL,
    DNI_CLIENTE VARCHAR(9) NOT NULL,
    CONSTRAINT PK_VENTA PRIMARY KEY(CODVENTA),
    CONSTRAINT FK_VENDEDOR_DNI FOREIGN KEY(DNI_VENDEDOR) REFERENCES VENDEDOR(DNI_VENDEDOR),
    CONSTRAINT FK_CLIENTE_DNI FOREIGN KEY(DNI_CLIENTE) REFERENCES CLIENTE(DNI_CLIENTE)
)

CREATE TABLE FAMILIA(
    COD_FAMILIA NUMBER(4),
    CONSTRAINT PK_FAMILIA PRIMARY KEY(COD_FAMILIA)
);

CREATE TABLE GENERO(
    COD_GENERO NUMBER(4),
    CONSTRAINT PK_GENERO PRIMARY KEY(COD_GENERO)
);

CREATE TABLE PRODUCTO(
    COD_PRODUCTO NUMBER(4),
    DESCRIPCION VARCHAR(30) NOT NULL,
    DESCUENTO NUMBER(4,2) DEFAULT 0,
    IVA NUMBER(2) NOT NULL,
    COD_FAMILIA NUMBER(4) NOT NULL,
    COD_GENERO NUMBER(4) NOT NULL,
    CONSTRAINT PK_PRODUCTO PRIMARY KEY(COD_PRODUCTO),
    CONSTRAINT FK_GENERO FOREIGN KEY(COD_GENERO) REFERENCES GENERO(COD_GENERO),
    CONSTRAINT FK_FAMILIA FOREIGN KEY(COD_FAMILIA) REFERENCES FAMILIA(COD_FAMILIA),
    CONSTRAINT CK_DESCUENTO CHECK(DESCUENTO > 0 AND DESCUENTO < 100),
    CONSTRAINT CK_IVA CHECK(IVA IN (4,10,21))
);

CREATE TABLE LINEAVENTA(
    CODVENTA NUMBER(3) NOT NULL,
    NUMLINEAVENTA NUMBER(2) NOT NULL,
    CANTIDAD NUMBER(2) NOT NULL,
    CONSTRAINT PK_LINEAVENTA PRIMARY KEY(CODVENTA, NUMLINEAVENTA),
    CONSTRAINT FK_CODVENTA FOREIGN KEY (CODVENTA) REFERENCES VENTA (CODVENTA)
);