CREATE TABLE DIRECTOR(
    DNI_DIRECTOR VARCHAR(9)NOT NULL,
    NOMBRE VARCHAR(40)NOT NULL,
    APELLIDO1 VARCHAR(40)NOT NULL,
    APELLIDO2 VARCHAR(40)NULL,
    DOMICILIO VARCHAR(40)NOT NULL,
    EMAIL VARCHAR(40)NULL,
    CONSTRAINT PK_DIRECTOR PRIMARY KEY(DNI_DIRECTOR)
);

CREATE TABLE SUPERMERCADO(
    CODSUPERMERCADO NUMBER(3)NOT NULL,
    DIRECCION VARCHAR(40)NOT NULL,
    SUPERFICIE NUMBER(9)NOT NULL,
    ESALQUILER BOOLEAN,
    FECHA DATE NOT NULL,
    DNI_DIRECTOR VARCHAR(9)NOT NULL,
    CONSTRAINT PK_SUPERMERCADO PRIMARY KEY(CODSUPERMERCADO),
    CONSTRAINT FK_DIRECTOR FOREIGN KEY(DNI_DIRECTOR) REFERENCES DIRECTOR(DNI_DIRECTOR)
);

CREATE TABLE VENDEDOR(
    DNI_VENDEDOR VARCHAR(9)NOT NULL,
    NOMBRE VARCHAR(40)NOT NULL,
    APELLIDO1 VARCHAR(40)NOT NULL,
    APELLIDO2 VARCHAR(40)NULL,
    DOMICILIO VARCHAR(40)NOT NULL,
    EMAIL VARCHAR(40)NULL,
    CODSUPERMERCADO NUMBER(3)NOT NULL,
    CONSTRAINT PK_VENDEDOR PRIMARY KEY(DNI_VENDEDOR),
    CONSTRAINT FK_SUPERMERCADO FOREIGN KEY(CODSUPERMERCADO)REFERENCES SUPERMERCADO(CODSUPERMERCADO)
);

CREATE TABLE CLIENTE(
    DNI_CLIENTE VARCHAR(9)NOT NULL,
    NOMBRE VARCHAR(40)NOT NULL,
    APELLIDO1 VARCHAR(40)NOT NULL,
    APELLIDO2 VARCHAR(40)NULL,
    DOMICILIO VARCHAR(40)NOT NULL,
    EMAIL VARCHAR(40)NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY(DNI_CLIENTE)
);
