CREATE TABLE OFICINA (
    COD_OFICINA NUMBER(3) NOT NULL,
    DIRECCION VARCHAR(30) NOT NULL,
    TELEFONO NUMBER(9) NOT NULL,
    DNI_COMERCIAL VARCHAR(9) NOT NULL,
    DNI_DIRECTOR VARCHAR(9) NOT NULL,
    CONSTRAINT PK_OFICINA PRIMARY KEY(COD_OFICINA),
    CONSTRAINT FK_DIRECTOR FOREIGN KEY(DNI_DIRECTOR) REFERENCES DIRECTOR(DNI_DIRECTOR) ON DELETE CASCADE,
    CONSTRAINT CK_OFICINA CHECK(LENGTH(TELEFONO)=9)
);

CREATE TABLE COMERCIAL(
    DNI_COMERCIAL VARCHAR(9) NOT NULL,
    COMISION NUMBER(3) NOT NULL,
    COD_OFICINA NUMBER(3) NOT NULL,
    CONSTRAINT PK_COMERCIAL PRIMARY KEY(DNI_COMERCIAL),
    CONSTRAINT FK_DATOSPERSONALES FOREIGN KEY(DNI_COMERCIAL) REFERENCES DATOSPERSONALES(DNI) ON DELETE CASCADE,
    CONSTRAINT CK_COMISION CHECK(COMISION>0 AND COMISION<100)
);

ALTER TABLE OFICINA ADD CONSTRAINT FK_COMERCIAL FOREIGN KEY(DNI_COMERCIAL) REFERENCES COMERCIAL(DNI_COMERCIAL) ON DELETE CASCADE;

ALTER TABLE COMERCIAL ADD CONSTRAINT FK_OFICINA FOREIGN KEY(COD_OFICINA) REFERENCES OFICINA(COD_OFICINA) ON DELETE CASCADE;

CREATE TABLE VENDEDOR(
    DNI_VENDEDOR VARCHAR(9) NOT NULL,
    TURNO VARCHAR(6) NOT NULL,
    COD_OFICINA NUMBER(3) NOT NULL,
    CONSTRAINT PK_VENDEDOR PRIMARY KEY(DNI_VENDEDOR),
    CONSTRAINT FK_DATOSPERSONALES FOREIGN KEY(DNI_VENDEDOR) REFERENCES DATOSPERSONALES(DNI) ON DELETE CASCADE,
    CONSTRAINT FK_OFICINA FOREIGN KEY(COD_OFICINA) REFERENCES OFICINA(COD_OFICINA) ON DELETE CASCADE,
    CONSTRAINT CK_TURNO CHECK(TURNO IN('MAÑANA','TARDE','NOCHE'))
);